language: node_js
node_js: node
services: mongodb
notifications:
  webhooks:
    urls:
      secure: zp5O9mhETPTunPWOgWHYbpW8Ohvyhax6fzJyB/CNNivTfBERGPCyTFkuJVKoea4BdOqNkGjNXTO+/DqviAIZK5wZN/FbGtmamu6haoTcyh64RLmjCJ2VooSbDA/dnepL+f4KBkbl7G3+jVKnFkkd81tcWSEnVUH4qzEM6dPRk1MfjcGH9TAl0gvVMGGd/GVPG1RMEH6gwD+Hi2CwpNet6NSwdwJL9hDyOrEekZ3zmYqPqgfnZd7AIQ41RSOS0d6oT/gvconBEnK0mx3+KZmwHSAS+s2XcARK+55rG38xJvbjVRBhxkEOv/HXkteBgX0wbdtBKiT0utTbWmvaPU625vEdhbsSyCrpayNnQoF3tMQS3mFlGf004uk/IIw2uxlhvR76JVchrevWzB08LUEHFY+92GsNxIbWN9SB3W2tIs1bx1iCaGOF8xgZLIdXAUOBB4kbuZiN1jD7yssRnH6RrsxU2uuTVi7h7P4btEJhwxaUSeTLOgEEENxnBTbqVF1BUS50SI1nkuGBNyxFYv2eaDqXpHmrYgpztRKmCVCKvpcqFdJRywUi8TZmFSjx61iFwKzZQ93YRnHs72hOHjju89dOjdTI96BISQ4WaFRPzMDbQf3D/XVBa+OkFGrGQ33PZ0y1NwAA1EfMOLHm7Nwdl9KvCAq+wM8xUgefgr1V5as=
env:
- MONGODB_URI=mongodb://localhost:27017/instant-meetup APP_SECRET=OurSecretThing
